language: go
sudo: false
go:
  - 1.5
  - 1.6
  - tip
before_install:
  - npm install -g bower
  - bower install
install: make bindata
script:
  - go get -t -v ./...
  - go tool vet .
  - go test -v -race ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
