on: [push, pull_request]

name: Tests

jobs:
  test:
    name: Go Test
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
        id: go-setup
      - uses: actions/checkout@v2
      - run: go test -v ./...
