on: [push, pull_request]

name: Tests

jobs:
  test:
    name: Go Test
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
        id: go-setup
      - uses: actions/checkout@v2
      - run: git branch
      - run: cat handlers.go
      - run: go test -v ./...
